asm ".entry"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "call @__init"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
int __getmainargs(int *argc,char ***argv);
asm "@__getmainargs"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "pushq $0"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "xor %r8d,%r8d"
asm "mov $1,%r9d"
asm "push %r8"
asm "lea 8(%rsp),%r8"
asm "push %r8"
asm "push %r9"
asm "lea 16(%rsp),%r8"
asm "push %r8"
asm "push %rdx"
asm "push %rcx"
asm ".dllcall \"msvcrt.dll\" \"__getmainargs\""
asm "add $48,%rsp"
asm "add $256,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
int _main(int argc,char **argv,void *hInstance);
asm "@_main"
asm "jmp @main"
void PostQuitMessage(int code);
asm "@PostQuitMessage"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "sub $32,%rsp"
asm ".dllcall \"user32.dll\" \"PostQuitMessage\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
int __init(void)
{
	int argc;
	char **argv;
	if(__getmainargs(&argc,&argv))
	{
		return -1;
	}
	return _main(argc,argv,(void *)0x400000);
}
int MessageBoxA(void *hwnd,char *msg,char *title,int style);
asm "@MessageBoxA"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "mov 32(%rbp),%r8"
asm "mov 40(%rbp),%r9"
asm "sub $32,%rsp"
asm ".dllcall \"user32.dll\" \"MessageBoxA\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"

long clock(void);
asm "@clock"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "sub $32,%rsp"
asm ".dllcall \"msvcrt.dll\" \"clock\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
int RegisterClassExA(void *wc);
asm "@RegisterClassExA"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "sub $32,%rsp"
asm ".dllcall \"user32.dll\" \"RegisterClassExA\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
void *LoadIconA(void *hInstance,char *name);
asm "@LoadIconA"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "sub $32,%rsp"
asm ".dllcall \"user32.dll\" \"LoadIconA\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
void *LoadCursorA(void *hInstance,char *name);
asm "@LoadCursorA"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "sub $32,%rsp"
asm ".dllcall \"user32.dll\" \"LoadCursorA\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
void *CreateWindowExA(unsigned int exstyle,char *classname,char *windowname,unsigned int style,
		int x,int y,int w,int h,void *parent,void *menu,void *hInstance,void *param);
asm "@CreateWindowExA"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "mov 32(%rbp),%r8"
asm "mov 40(%rbp),%r9"
asm "pushq 104(%rbp)"
asm "pushq 96(%rbp)"
asm "pushq 88(%rbp)"
asm "pushq 80(%rbp)"
asm "pushq 72(%rbp)"
asm "pushq 64(%rbp)"
asm "pushq 56(%rbp)"
asm "pushq 48(%rbp)"
asm "sub $32,%rsp"
asm ".dllcall \"user32.dll\" \"CreateWindowExA\""
asm "add $96,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
int GetMessageA(void *msg,void *hwnd,unsigned int filtermin,unsigned int filtermax);
asm "@GetMessageA"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "mov 32(%rbp),%r8"
asm "mov 40(%rbp),%r9"
asm "sub $32,%rsp"
asm ".dllcall \"user32.dll\" \"GetMessageA\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
int TranslateMessage(void *msg);
asm "@TranslateMessage"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "sub $32,%rsp"
asm ".dllcall \"user32.dll\" \"TranslateMessage\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
int DispatchMessageA(void *msg);
asm "@DispatchMessageA"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "sub $32,%rsp"
asm ".dllcall \"user32.dll\" \"DispatchMessageA\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
int DefWindowProcA(void *hwnd,unsigned int message,unsigned long wparam,unsigned long lparam);
asm "@DefWindowProcA"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "mov 32(%rbp),%r8"
asm "mov 40(%rbp),%r9"
asm "sub $32,%rsp"
asm ".dllcall \"user32.dll\" \"DefWindowProcA\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
void *GetDC(void *hwnd);
asm "@GetDC"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "sub $32,%rsp"
asm ".dllcall \"user32.dll\" \"GetDC\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
void *CreateCompatibleDC(void *dc);
asm "@CreateCompatibleDC"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "sub $32,%rsp"
asm ".dllcall \"gdi32.dll\" \"CreateCompatibleDC\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
void *CreateCompatibleBitmap(void *dc,int cx,int cy);
asm "@CreateCompatibleBitmap"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "mov 32(%rbp),%r8"
asm "sub $32,%rsp"
asm ".dllcall \"gdi32.dll\" \"CreateCompatibleBitmap\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
void *SelectObject(void *dc,void *obj);
asm "@SelectObject"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "sub $32,%rsp"
asm ".dllcall \"gdi32.dll\" \"SelectObject\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
void *BitBlt(void *dc,int x,int y,int cx,int cy,void *src,int x0,int y0,int mode);
asm "@BitBlt"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "mov 32(%rbp),%r8"
asm "mov 40(%rbp),%r9"
asm "sub $8,%rsp"
asm "pushq 80(%rbp)"
asm "pushq 72(%rbp)"
asm "pushq 64(%rbp)"
asm "pushq 56(%rbp)"
asm "pushq 48(%rbp)"
asm "sub $32,%rsp"
asm ".dllcall \"gdi32.dll\" \"BitBlt\""
asm "add $80,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
void *BeginPaint(void *hwnd,void *ps);
asm "@BeginPaint"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "sub $32,%rsp"
asm ".dllcall \"user32.dll\" \"BeginPaint\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
int EndPaint(void *hwnd,void *ps);
asm "@EndPaint"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "sub $32,%rsp"
asm ".dllcall \"user32.dll\" \"EndPaint\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
void *CreateThread(void *sattr,long stack_size,void *fun,void *param,int flags,void *id);
asm "@CreateThread"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "mov 32(%rbp),%r8"
asm "mov 40(%rbp),%r9"
asm "pushq 56(%rbp)"
asm "pushq 48(%rbp)"
asm "sub $32,%rsp"
asm ".dllcall \"kernel32.dll\" \"CreateThread\""
asm "add $48,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
long SetBitmapBits(void *bmp,int cb,void *ptr);
asm "@SetBitmapBits"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "mov 32(%rbp),%r8"
asm "sub $32,%rsp"
asm ".dllcall \"gdi32.dll\" \"SetBitmapBits\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
long CreateMutexA(void *sattr,int init,char *name);
asm "@CreateMutexA"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "mov 32(%rbp),%r8"
asm "sub $32,%rsp"
asm ".dllcall \"kernel32.dll\" \"CreateMutexA\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
void *WaitForSingleObject(void *obj,int msec);
asm "@WaitForSingleObject"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "sub $32,%rsp"
asm ".dllcall \"kernel32.dll\" \"WaitForSingleObject\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
void Sleep(int msec);
asm "@Sleep"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "sub $32,%rsp"
asm ".dllcall \"kernel32.dll\" \"Sleep\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
int ReleaseMutex(void *mutex);
asm "@ReleaseMutex"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "sub $32,%rsp"
asm ".dllcall \"kernel32.dll\" \"ReleaseMutex\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
void *malloc(unsigned long size);
asm "@malloc"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "add $32,%rcx"
asm "sub $32,%rsp"
asm ".dllcall \"msvcrt.dll\" \"malloc\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
void free(void *ptr);
asm "@free"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "sub $32,%rsp"
asm ".dllcall \"msvcrt.dll\" \"free\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
unsigned int GetCurrentDirectory(unsigned int len,char *ptr);
asm "@GetCurrentDirectory"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "sub $32,%rsp"
asm ".dllcall \"kernel32.dll\" \"GetCurrentDirectoryA\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
unsigned int SetCurrentDirectory(char *name);
asm "@SetCurrentDirectory"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "sub $32,%rsp"
asm ".dllcall \"kernel32.dll\" \"SetCurrentDirectoryA\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
long SetTimer(void *hwnd,long id,unsigned int elapse,void *cb);
asm "@SetTimer"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "mov 32(%rbp),%r8"
asm "mov 40(%rbp),%r9"
asm "sub $32,%rsp"
asm ".dllcall \"user32.dll\" \"SetTimer\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
long GetWindowRect(void *hwnd,void *ret);
asm "@GetWindowRect"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "sub $32,%rsp"
asm ".dllcall \"user32.dll\" \"GetWindowRect\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
long DeleteObject(void *obj);
asm "@DeleteObject"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "sub $32,%rsp"
asm ".dllcall \"gdi32.dll\" \"DeleteObject\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
long DeleteDC(void *dc);
asm "@DeleteDC"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "sub $32,%rsp"
asm ".dllcall \"gdi32.dll\" \"DeleteDC\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
int CreateDirectoryA(char *name,void *sa);
asm "@CreateDirectoryA"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "sub $16,%rsp"
asm "push %rdx"
asm "push %rcx"
asm ".dllcall \"kernel32.dll\" \"CreateDirectoryA\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
int RemoveDirectoryA(char *name);
asm "@RemoveDirectoryA"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "sub $24,%rsp"
asm "push %rcx"
asm ".dllcall \"kernel32.dll\" \"RemoveDirectoryA\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"

void *FindFirstFileA(char *name,void *data);
asm "@FindFirstFileA"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "sub $16,%rsp"
asm "push %rdx"
asm "push %rcx"
asm ".dllcall \"kernel32.dll\" \"FindFirstFileA\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
int FindNextFileA(void *dh,void *data);
asm "@FindNextFileA"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "sub $16,%rsp"
asm "push %rdx"
asm "push %rcx"
asm ".dllcall \"kernel32.dll\" \"FindNextFileA\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
int FindClose(void *dh);
asm "@FindClose"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "sub $24,%rsp"
asm "push %rcx"
asm ".dllcall \"kernel32.dll\" \"FindClose\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
unsigned int GetLogicalDrives(void);
asm "@GetLogicalDrives"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "sub $24,%rsp"
asm "push %rcx"
asm ".dllcall \"kernel32.dll\" \"GetLogicalDrives\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
void *MoveWindow(void *hwnd,int x,int y,int w,int h,long redraw);
asm "@MoveWindow"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "mov 32(%rbp),%r8"
asm "mov 40(%rbp),%r9"
asm "pushq 56(%rbp)"
asm "pushq 48(%rbp)"
asm "sub $32,%rsp"
asm ".dllcall \"user32.dll\" \"MoveWindow\""
asm "add $48,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
int ShowWindow(void *hwnd,int cmd);
asm "@ShowWindow"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "sub $16,%rsp"
asm "push %rdx"
asm "push %rcx"
asm ".dllcall \"user32.dll\" \"ShowWindow\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
int CloseHandle(void *h);
asm "@CloseHandle"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "sub $24,%rsp"
asm "push %rcx"
asm ".dllcall \"kernel32.dll\" \"CloseHandle\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
int system(char *str);
asm "@system"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "sub $24,%rsp"
asm "push %rcx"
asm ".dllcall \"msvcrt.dll\" \"system\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"

void T_exec_program(char *str)
{
	system(str);
}
void _T_exec_program(void);
asm "@_T_exec_program"
asm "push %rcx"
asm "call @T_exec_program"
asm "xor %eax,%eax"
asm "add $8,%rsp"
asm "ret"
unsigned long strlen(char *str);
char *strcpy(char *dst,char *src);
void exec_program(char *str)
{
	void *handle;
	char *new_str;
	new_str=malloc(strlen(str)+1);
	if(new_str==0)
	{
		return;
	}
	strcpy(new_str,str);
	handle=CreateThread(0,0,_T_exec_program,new_str,0,0);
	if(handle==0)
	{
		free(new_str);
		return;
	}
	CloseHandle(handle);
}
void *fopen(char *name,char *mode);
asm "@fopen"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "sub $16,%rsp"
asm "push %rdx"
asm "push %rcx"
asm ".dllcall \"msvcrt.dll\" \"fopen\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
int fclose(void *fp);
asm "@fclose"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "sub $24,%rsp"
asm "push %rcx"
asm ".dllcall \"msvcrt.dll\" \"fclose\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
int fread(void *buf,int size,int count,void *fp);
asm "@fread"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "mov 32(%rbp),%r8"
asm "mov 40(%rbp),%r9"
asm "push %r9"
asm "push %r8"
asm "push %rdx"
asm "push %rcx"
asm ".dllcall \"msvcrt.dll\" \"fread\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
int fwrite(void *buf,int size,int count,void *fp);
asm "@fwrite"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "mov 32(%rbp),%r8"
asm "mov 40(%rbp),%r9"
asm "push %r9"
asm "push %r8"
asm "push %rdx"
asm "push %rcx"
asm ".dllcall \"msvcrt.dll\" \"fwrite\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
int rename(char *path,char *new_name);
asm "@rename"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "mov 24(%rbp),%rdx"
asm "sub $16,%rsp"
asm "push %rdx"
asm "push %rcx"
asm ".dllcall \"msvcrt.dll\" \"rename\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"
int remove(char *name);
asm "@remove"
asm "push %rbp"
asm "mov %rsp,%rbp"
asm "and $0xf0,%spl"
asm "push %r8"
asm "push %r9"
asm "push %r10"
asm "push %r11"
asm "mov 16(%rbp),%rcx"
asm "sub $24,%rsp"
asm "push %rcx"
asm ".dllcall \"msvcrt.dll\" \"remove\""
asm "add $32,%rsp"
asm "pop %r11"
asm "pop %r10"
asm "pop %r9"
asm "pop %r8"
asm "mov %rbp,%rsp"
asm "pop %rbp"
asm "ret"


